### ISSUE TITLE
Review Drand docs, create new map for docs structure.

### ISSUE THREAD

**Issue by johnnymatthews** [drand/website#95]
This repository was created a while ago and hasn't seen many updates since its initial launch. The Drand project intends to reach more users and developers than those originally targeted when this project first started. 

With this in mind, let's review all the documentation within this site and create a plan to either update or deprecate pages. On top of that, let's create a general hierarchy/plan for the information structure of this repo.

## Tasks

- [ ] Create basic structure map/plan for Drand docs.
- [ ] Review existing content and see if it fits anywhere into the new map.
    - [ ] Existing pages may need to be split into multiple sections, updated, or deprecated if they are no longer valid.
    - [ ] Notes for individual pages can be left in this issue for safe-keeping.

This issue can serve as a dumping ground for ideas, plans, and discussion. This issue can be closed once we have a agreed upon a map for Drand docs.

**Comment by johnnymatthews** [comment]
Potential map for what the docs structure could look like.

```
Welcome
    What Drand is.
    Who the target audience is.
    Simple curl request to get randomness from a node.

Concepts
    Randomness 101
        Why randomness is useful
        Defining good randomness
        Use-cases
    How Drand works
        Phases
        Security
        Specification

Developers
    Quickstart
        Make a simple website that grabs the randomness and adds it into a diceroll or something.
    Go
    JavaScript

Node operators
    Deployment
    Docker
    Gather metrics
    
Reference
    HTTP API
    CLI

Project
    Who's creating it.
    Get help

```
